### ISSUE TITLE
Missing header file prevents pip installation

### ISSUE THREAD

**Issue by chadhanna** [duncanmmacleod/requests-ecp#8]
When doing pip install I see:

```
In file included from src/kerberos.c:19:0:
src/kerberosbasic.h:17:10: fatal error: gssapi/gssapi.h: No such file or directory
 #include <gssapi/gssapi.h>
```

which was fixed by doing: 

sudo apt-get install libkrb5-dev

Could this be added as a dependency?

**Comment by duncanmmacleod** [comment]
> Could this be added as a dependency?

Not really, since `pip` doesn't handle non-python dependencies well. The problem is that your `pip install` is trying to compile `pykerberos` on-the-fly, since that is a requirement of `requests-kerberos`.

The best solution is for you to use `conda` to install `requests-ecp` which will use only pre-compiled packages for `krb5` and `pykerberos` (and everything else). Alternatively, you could configure your `apt` to point at the lscdebian distribution maintained at AEI-Hannover and `apt-get install python3-requests-ecp`. See [this link](https://computing.docs.ligo.org/guide/software/installation/#lscdebian) for details on the `apt` configuration.
